(package "preview-it"
         "1.1.0"
         "Preview anything at point")

(website-url "https://github.com/jcs-elpa/preview-it")
(keywords "convenience" "preview" "image" "path" "file")

(package-file "preview-it.el")

(source "melpa")

(depends-on "emacs" "26.1")
(depends-on "posframe")
(depends-on "request")
(depends-on "gh-md")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
